Move projects to ancestors
chaoss/grimoirelab-bestiary pull request #75
Opened 2021-06-14 15:38 UTC by evamillan

Allows moving a project to a parent with a different root and to remove a project's parent, both from the GraphQL API and from the UI.
Fixes #74.

2021-06-15 08:42 UTC, sduenas requested changes
The PR looks good but you need to add some unit tests to the Python part to check the new cases. In addition, we starting using in bestiary the release-tools, that means you should add a changelog entry to `releases/unreleased` dir explaining the change.

2021-06-15 08:42 UTC, sduenas commented on bestiary/core/db.py
> +    if parent_project and (project.ecosystem != parent_project.ecosystem):
Unit tests should test that it's possible to remove the link a parent project setting it to `None`.

2021-06-15 08:42 UTC, sduenas commented on bestiary/core/api.py
> +        to_project = find_project(to_project_id) if to_project_id else None
You should add unit tests to check this case.

2021-06-15 15:43 UTC, evamillan commented
I've added the tests and the changelog entry.

2021-06-15 16:27 UTC, sduenas requested changes
LGTM. Just a minor suggestion (`None` and a blank line between docstring and code).

2021-06-15 16:27 UTC, sduenas commented on tests/test_api.py
> +        """Check if removes the parent project when none is given"""
```suggestion
        """Check if removes the parent project when None is given"""
        
```

2021-06-16 14:58 UTC, evamillan commented on tests/test_api.py
> +        """Check if removes the parent project when none is given"""
Thanks, I've changed it.

2021-06-16 19:17 UTC, sduenas approved these changes
LGTM

2021-06-16 19:18 UTC, merged