[server] Add support for managing data sources and data sets
chaoss/grimoirelab-bestiary pull request #82
Opened 2021-07-20 06:54 UTC by jjmerchante

This commit includes DataSource, DataSet and DataSourceType models and the initial migrations file as described in https://github.com/chaoss/grimoirelab-bestiary/issues/39

Every DataSet object must have a related project, a related data source, a category and can include some filters.

Every DataSource object must have a DataSourceType associated and an uri for the backend.

DataSourceType database must be filled with data with the supported data sources.

This commit also includes some methods at database level to:
- Find data sources
- Add data sources
- Delete data sources
- Find data sets
- Add data sets
- Date data sets
- Update data sets
  
This PR includes tests for each data base method

2021-07-21 16:57 UTC, sduenas requested changes
Some changes are needed. Also, you need to:

- Add tests for the model.
- Add `test_last_update` tests.
- I think we should use `datasource` instead of `data source` and the same with dataset. I know they aren't valid English words but in this case we are talking more about the objects we are storing. Not sure if this makes sense to you.

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/db.py
> +    """Find a data source
```suggestion
    """Find a data source.
```

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/db.py
> +    """Find a data set
```suggestion
    """Find a data set.
```

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/db.py
> +        filters.sort()
Is this possible? Shouldn't filters be a dict always?

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/db.py
> +                       target='Project(%s)DataSource(%s)' %
I would follow the same approach we have in [sortinghat](https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/sortinghat/core/db.py#L786), where the main target is only one. I think in this case it has to be `project`.

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/db.py
> +    data_set.delete()
I think we should add an operation here which is `data_set.project.save()`, so the project dates are also updated. Probably we will also need to do the same with the environment object. See it on: https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/sortinghat/core/db.py#L812

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/db.py
> +def link_data_set_project(trxl, data_set, project):
Why do we need this function?

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/models.py
> +    :param name: Name of the data source
```suggestion
    :param name: name of the data source
```

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/models.py
> +        db_table = 'datasourcetype'
```suggestion
        db_table = 'datasource_types'
```

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/models.py
> +        db_table = 'datasource'
```suggestion
        db_table = 'datasources'
```

2021-07-21 16:57 UTC, sduenas commented on bestiary/core/models.py
> +    #  with a project but related to an Ecosystem?
No, it can't.

2021-07-21 16:57 UTC, sduenas commented on tests/test_db.py
> +        dst = DataSourceType.objects.create(name='GitHub')
```suggestion
        """Load initial dataset"""
        
        dst = DataSourceType.objects.create(name='GitHub')
```

2021-07-21 16:57 UTC, sduenas commented on tests/test_db.py
> +class TestAddDataSource(TestCase):
I miss a test where you check that the operations log is correctly stored.

2021-07-21 16:57 UTC, sduenas commented on tests/test_db.py
> +        """Load initial dataset"""
```suggestion
        """Load initial dataset"""
        
```

2021-07-21 16:57 UTC, sduenas commented on tests/test_db.py
> +class TestAddDataSet(TestCase):
I miss here also a test to check the operations.

2021-07-21 16:57 UTC, sduenas commented on tests/test_db.py
> +                                            uri='https://github.com/chaoss/grimoirelab-bestiary')
Please tabulate these lines.

2021-07-22 06:50 UTC, jjmerchante commented on bestiary/core/models.py
> +    :param name: Name of the data source
I changed this and many others that started with capital letter aftert `:`

2021-07-22 06:50 UTC, jjmerchante commented on bestiary/core/db.py
> +def link_data_set_project(trxl, data_set, project):
I created this function in case someone wants to move the data set to a different project.

2021-07-22 06:50 UTC, jjmerchante commented on bestiary/core/db.py
> +    data_set.delete()
Ok, it seems better. When you say environment object you mean ecosystem?

2021-07-22 06:50 UTC, jjmerchante commented on bestiary/core/db.py
> +        filters.sort()
I changed the implementation to make sure filters are always dict

2021-07-22 07:15 UTC, jjmerchante commented
> I think we should use datasource instead of data source and the same with dataset. I know they aren't valid English words but in this case we are talking more about the objects we are storing. Not sure if this makes sense to you.

I had this discussion some time ago with Jesus and Manrique in a different context and we decided to go for data_source. Anyway it is something internal to the code and I don't see any problem going your way.

In commentaries I keep `data source` and `data set`, and I also keep class names as DataSource and DataSet. I rename only the attributes of the classes and any word written as `data_source` to `datasource` (and the same for data set)

2021-07-22 11:30 UTC, sduenas commented on bestiary/core/db.py
> +    data_set.delete()
Yes, ecosystem sorry :(.

2021-07-22 11:33 UTC, sduenas commented
> > I think we should use datasource instead of data source and the same with dataset. I know they aren't valid English words but in this case we are talking more about the objects we are storing. Not sure if this makes sense to you.
> 
> I had this discussion some time ago with Jesus and Manrique in a different context and we decided to go for data_source. Anyway it is something internal to the code and I don't see any problem going your way.
> 
> In commentaries I keep `data source` and `data set`, and I also keep class names as DataSource and DataSet. I rename only the attributes of the classes and any word written as `data_source` to `datasource` (and the same for data set)

Yes, in the comments is maybe better to reference as _data source_ and _data set_ but in methods, parameters, etc better to have `datasource` and `dataset` because we consider it as a whole.

2021-07-22 11:39 UTC, jjmerchante commented
Changes in the last push:
- Tests for models
- Changed all `data_source` and `data_set` to `datasource` and `dataset` in variables and function names
- Included some missing `last_modified` and `operations` tests
- Save the project and ecosystem whenever a project or a dataset is added or updated (I forgot to include tests related with this, I include them later)

2021-07-22 12:14 UTC, sduenas requested changes
In overall it looks good but please, check my comments to approve it.

2021-07-22 12:14 UTC, sduenas commented on bestiary/core/db.py
> +        if project.ecosystem:
I think this is not needed because the project is saved so it should have the ecosystem assigned, isn't true?

2021-07-22 12:14 UTC, sduenas commented on bestiary/core/db.py
> +    """Add an data set to the database.
```suggestion
    """Add a data set to the database.
```

2021-07-22 12:14 UTC, sduenas commented on bestiary/core/db.py
> +        else:
This can be more readable if you put the `ifinstance` first on the if block.

2021-07-22 12:14 UTC, sduenas commented on bestiary/core/db.py
> +def link_dataset_project(trxl, dataset, project):
I don't see unit tests for this function.

2021-07-22 13:00 UTC, jjmerchante commented on bestiary/core/db.py
> +        if project.ecosystem:
Yes, you are right. I don't understand the null attribute in `Project.ecosystem` field. Reading the code it seems there shouldn't be a project without an ecosystem.

I could remove `if project.ecosytem` in the other functions if that `null=True` wasn't there.

2021-07-22 16:46 UTC, sduenas approved these changes
LGTM

2021-07-22 16:54 UTC, sduenas requested changes
I got this error running the tests:

```
Traceback (most recent call last):
  File "/home/sduenas/devel/envs/beast/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sduenas/devel/envs/beast/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/sduenas/devel/envs/beast/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/sduenas/devel/envs/beast/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/sduenas/devel/envs/beast/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1170, "BLOB/TEXT column 'filters' used in key specification without a key length")
```

I think this is related: https://stackoverflow.com/questions/57004837/blob-text-column-used-in-key-specification-without-a-key-length-error-in-djang

2021-07-23 15:54 UTC, sduenas approved these changes
Great. LGTM.

2021-07-23 15:54 UTC, merged