Implement API methods to create and remove data sets
chaoss/grimoirelab-bestiary pull request #84
Opened 2021-08-02 14:59 UTC by jjmerchante

This Pull request includes the following changes:
- The implementation didn't allow to have Projects without Ecosystems but it models it was allowed. Remove in this pull requests the `null=True` attribute in Ecosystem and fix some tests that weren't using a default Ecosystem.
- New API method to add datasets as it was defined in https://github.com/chaoss/grimoirelab-bestiary/issues/39
- New API method to remove datasets by id
- GraphQL query to get dataset objects. It includes filters and pagination methods.
- GraphQL mutation to delete a dataset object by ID.

Every change has its related tests.

2021-08-03 12:22 UTC, sduenas requested changes
In overall it looks good to me. There are some comments to be addressed, though.

2021-08-03 12:22 UTC, sduenas commented on tests/test_api.py
> +        api.delete_dataset(self.ctx, dataset_id=self.dataset_2.id)
Leave an empty line between the code and the docstring.

2021-08-03 12:22 UTC, sduenas commented on tests/test_api.py
> +        dataset_1 = api.add_dataset(self.ctx,
Leave an empty line between the code and the docstring.

2021-08-03 12:22 UTC, sduenas commented on bestiary/core/schema.py
> +    category = graphene.String(required=False)
Can you add some documentation about these fields? You can check in sortinghat how to do it: https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/sortinghat/core/schema.py#L275

2021-08-04 06:08 UTC, jjmerchante commented
I have a question about the JSONField. I have included some tests that now fail, but I don't understand why.

As far as I understand there is a function to serialize the JSONFields and it is registered with `@convert_django_field.register(JSONField)`. It works for `Operation.args` but it doesn't work for `Dataset.filters` by default. I don't know what I'm missing.

2021-08-04 07:22 UTC, sduenas commented
> I have a question about the JSONField. I have included some tests that now fail, but I don't understand why.
> 
> As far as I understand there is a function to serialize the JSONFields and it is registered with `@convert_django_field.register(JSONField)`. It works for `Operation.args` but it doesn't work for `Dataset.filters` by default. I don't know what I'm missing.

What's the error you are getting?

2021-08-04 07:36 UTC, jjmerchante commented
Debugging, the error is returned here:
```
executed = client.execute(BT_DATASETS_QUERY,
                          context_value=self.context_value)
datasets = executed['data']['datasets']['entities']
```
```
{'errors': [{'message': 'the JSON object must be str, bytes or bytearray, not dict'}], 'data': {'datasets': {'entities': [None]}}}
```
and debugging a bit more it raises here: https://github.com/chaoss/grimoirelab-bestiary/blob/unicorn/bestiary/core/schema.py#L99

The value is a dictionary and it expects an string. I see that in Operations the JSONField is stored as a string instead of a dictionary: https://github.com/chaoss/grimoirelab-bestiary/blob/3e26e65583ab65ccddf795d52b290922bae5985a/bestiary/core/log.py#L139, so I guess I should do the same for the Dataset (store filters as string in the JSONField)

2021-08-04 11:29 UTC, sduenas approved these changes
LGTM

2021-08-04 11:33 UTC, sduenas requested changes
The code looks ok but I forgot something. Can you add a changelog entry to keep track of the changes. See this file for more info: https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/CONTRIBUTING.md . You have also some examples in: https://github.com/chaoss/grimoirelab-bestiary/tree/unicorn/releases/unreleased

2021-08-04 14:43 UTC, sduenas approved these changes
LGTM

2021-08-04 14:44 UTC, merged